await 0
throw new Error('already-errored');
